# Generated by Django 5.2 on 2025-05-31 02:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikels', '0003_alter_artikelblog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikelblog',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
