# Generated by Django 5.2 on 2025-05-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikels', '0004_alter_artikelblog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikelblog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
